//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/request/QueryGeoObject.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLonRect;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/request/gen/QueryGeoObjectGen.h"

@interface DeGminoGeobaseSharedRequestQueryGeoObject : DeGminoGeobaseSharedRequestGenQueryGeoObjectGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithDeGminoGeobaseSharedDomainLatLonRect:(DeGminoGeobaseSharedDomainLatLonRect *)area
                                           withInt:(int)maxCount;
@end
