//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/Comment.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/Timestamp.h"
#import "de/gmino/issuemap/shared/domain/Comment.h"
#import "de/gmino/issuemap/shared/domain/Issue.h"

@implementation DeGminoIssuemapSharedDomainComment

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapSharedDomainIssue:(DeGminoIssuemapSharedDomainIssue *)issue
         withNSString:(NSString *)text
         withNSString:(NSString *)user
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)timestamp
             withBOOL:(BOOL)deleted {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoIssuemapSharedDomainIssue:(DeGminoIssuemapSharedDomainIssue *) issue withNSString:text withNSString:user withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *) timestamp withBOOL:deleted])) {
    self.ready = YES;
  }
  return self;
}

@end
