//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/Issue.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainImageUrl;
@class DeGminoGeobaseSharedDomainLatLon;
@class DeGminoGeobaseSharedDomainTimestamp;
@class DeGminoIssuemapSharedDomainMap;
@class DeGminoIssuemapSharedDomainMarkertype;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/domain/gen/IssueGen.h"

@interface DeGminoIssuemapSharedDomainIssue : DeGminoIssuemapSharedDomainGenIssueGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *)markertype
withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *)map_instance
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)creationTimestamp
              withInt:(int)rating
              withInt:(int)number_of_rating
             withBOOL:(BOOL)resolved
             withBOOL:(BOOL)deleted
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)primary_picture
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)eventTimestamp
           withDouble:(double)price
         withNSString:(NSString *)organizer
         withNSString:(NSString *)email
         withNSString:(NSString *)phone;
@end
