//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/Issue.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/ImageUrl.h"
#import "de/gmino/geobase/shared/domain/LatLon.h"
#import "de/gmino/geobase/shared/domain/Timestamp.h"
#import "de/gmino/issuemap/shared/domain/Issue.h"
#import "de/gmino/issuemap/shared/domain/Map.h"
#import "de/gmino/issuemap/shared/domain/Markertype.h"

@implementation DeGminoIssuemapSharedDomainIssue

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *)markertype
withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *)map_instance
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)creationTimestamp
              withInt:(int)rating
              withInt:(int)number_of_rating
             withBOOL:(BOOL)resolved
             withBOOL:(BOOL)deleted
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)primary_picture
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)eventTimestamp
           withDouble:(double)price
         withNSString:(NSString *)organizer
         withNSString:(NSString *)email
         withNSString:(NSString *)phone {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *) location withNSString:title withNSString:description_ withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *) markertype withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *) map_instance withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *) creationTimestamp withInt:rating withInt:number_of_rating withBOOL:resolved withBOOL:deleted withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *) primary_picture withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *) eventTimestamp withDouble:price withNSString:organizer withNSString:email withNSString:phone])) {
    self.ready = YES;
  }
  return self;
}

@end
