//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/Map.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainImageUrl;
@class DeGminoGeobaseSharedDomainLatLon;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/domain/gen/MapGen.h"

@interface DeGminoIssuemapSharedDomainMap : DeGminoIssuemapSharedDomainGenMapGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
         withNSString:(NSString *)subdomain
         withNSString:(NSString *)color
         withNSString:(NSString *)city
withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)initLocation
              withInt:(int)initZoomlevel
         withNSString:(NSString *)layer
         withNSString:(NSString *)headerText
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)logo
         withNSString:(NSString *)infoText
         withNSString:(NSString *)mapTyp;
@end
