//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/MapHasMarkertype.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoIssuemapSharedDomainMap;
@class DeGminoIssuemapSharedDomainMarkertype;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/domain/gen/MapHasMarkertypeGen.h"

@interface DeGminoIssuemapSharedDomainMapHasMarkertype : DeGminoIssuemapSharedDomainGenMapHasMarkertypeGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *)markertype
withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *)map;
@end
