//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/MapHasMarkertype.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/issuemap/shared/domain/Map.h"
#import "de/gmino/issuemap/shared/domain/MapHasMarkertype.h"
#import "de/gmino/issuemap/shared/domain/Markertype.h"

@implementation DeGminoIssuemapSharedDomainMapHasMarkertype

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *)markertype
withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *)map {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoIssuemapSharedDomainMarkertype:(DeGminoIssuemapSharedDomainMarkertype *) markertype withDeGminoIssuemapSharedDomainMap:(DeGminoIssuemapSharedDomainMap *) map])) {
    self.ready = YES;
  }
  return self;
}

@end
