//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/domain/Photo.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainImageUrl;
@class DeGminoGeobaseSharedDomainTimestamp;
@class DeGminoIssuemapSharedDomainIssue;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/domain/gen/PhotoGen.h"

@interface DeGminoIssuemapSharedDomainPhoto : DeGminoIssuemapSharedDomainGenPhotoGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapSharedDomainIssue:(DeGminoIssuemapSharedDomainIssue *)issue
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)image
         withNSString:(NSString *)user
withDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)timestamp
             withBOOL:(BOOL)deleted;
@end
