//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/request/NetworkRequests.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoMevaSharedEntityTypeName;
@class DeGminoMevaSharedRequestRequestListener;
@protocol DeGminoMevaSharedEntityQuery;
@protocol DeGminoMevaSharedValueQuery;
@protocol JavaUtilCollection;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedRequestNetworkRequests < NSObject >
- (void)getIdsByQueryWithDeGminoMevaSharedEntityQuery:(id<DeGminoMevaSharedEntityQuery>)query
          withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
- (void)getValuesByQueryWithDeGminoMevaSharedValueQuery:(id<DeGminoMevaSharedValueQuery>)query
            withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
- (void)getNewIdsWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                             withInt:(int)count
         withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
- (void)loadEntitiesWithJavaUtilCollection:(id<JavaUtilCollection>)entities
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
- (void)saveEntitiesWithJavaUtilCollection:(id<JavaUtilCollection>)entities
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
@end
