//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/request/Requests.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoMevaSharedEntityTypeName;
@class JavaLangLong;
@class JavaLangThrowable;
@protocol DeGminoMevaSharedEntity;
@protocol DeGminoMevaSharedEntityQuery;
@protocol DeGminoMevaSharedRequestNetworkRequests;
@protocol DeGminoMevaSharedValueQuery;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "de/gmino/meva/shared/request/RequestListener.h"

@interface DeGminoMevaSharedRequestRequests : NSObject {
}

+ (id<DeGminoMevaSharedRequestNetworkRequests>)networkImpl;
+ (void)setNetworkImpl:(id<DeGminoMevaSharedRequestNetworkRequests>)networkImpl;
+ (void)setImplementationWithDeGminoMevaSharedRequestNetworkRequests:(id<DeGminoMevaSharedRequestNetworkRequests>)networkImpl;
+ (void)ensureImplementation;
+ (void)getIdsByQueryWithDeGminoMevaSharedEntityQuery:(id<DeGminoMevaSharedEntityQuery>)q
          withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getValuesByQueryWithDeGminoMevaSharedValueQuery:(id<DeGminoMevaSharedValueQuery>)query
            withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getLoadedEntityByIdWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                                   withLongInt:(long long int)id_
                   withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getLoadedEntitiesByIdWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                          withJavaUtilCollection:(id<JavaUtilCollection>)ids
                     withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getLoadedEntitiesByQueryWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                   withDeGminoMevaSharedEntityQuery:(id<DeGminoMevaSharedEntityQuery>)q
                        withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getNewEntityWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
            withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getNewEntitiesWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                                  withInt:(int)count
              withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getNewIdsWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                             withInt:(int)count
         withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)getUnloadedEntitiesByQueryWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                     withDeGminoMevaSharedEntityQuery:(id<DeGminoMevaSharedEntityQuery>)q
                          withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)loadEntityWithId:(id<DeGminoMevaSharedEntity>)entity
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)saveEntityWithId:(id<DeGminoMevaSharedEntity>)entity
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)loadEntitiesWithJavaUtilCollection:(id<JavaUtilCollection>)entities
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)saveEntitiesWithJavaUtilCollection:(id<JavaUtilCollection>)entities
withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)listener;
+ (void)ensureSameTypesWithJavaUtilCollection:(id<JavaUtilCollection>)entities;
- (id)init;
@end

@interface DeGminoMevaSharedRequestRequests_$1 : DeGminoMevaSharedRequestRequestListener {
 @public
  DeGminoMevaSharedEntityTypeName *val$type_;
  DeGminoMevaSharedRequestRequestListener *val$listener_;
}

@property (nonatomic, strong) DeGminoMevaSharedEntityTypeName *val$type;
@property (nonatomic, strong) DeGminoMevaSharedRequestRequestListener *val$listener;

- (void)onFinishedWithJavaUtilCollection:(id<JavaUtilCollection>)ids;
- (void)onErrorWithNSString:(NSString *)message
      withJavaLangThrowable:(JavaLangThrowable *)e;
- (id)initWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)capture$0
  withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)capture$1;
@end

@interface DeGminoMevaSharedRequestRequests_$2 : DeGminoMevaSharedRequestRequestListener {
 @public
  DeGminoMevaSharedEntityTypeName *val$type_;
  DeGminoMevaSharedRequestRequestListener *val$listener_;
}

@property (nonatomic, strong) DeGminoMevaSharedEntityTypeName *val$type;
@property (nonatomic, strong) DeGminoMevaSharedRequestRequestListener *val$listener;

- (void)onFinishedWithJavaUtilCollection:(id<JavaUtilCollection>)ids;
- (void)onNewResultWithId:(JavaLangLong *)result;
- (void)onErrorWithNSString:(NSString *)message
      withJavaLangThrowable:(JavaLangThrowable *)e;
- (id)initWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)capture$0
  withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)capture$1;
@end

@interface DeGminoMevaSharedRequestRequests_$3 : DeGminoMevaSharedRequestRequestListener {
 @public
  DeGminoMevaSharedEntityTypeName *val$type_;
  DeGminoMevaSharedRequestRequestListener *val$listener_;
}

@property (nonatomic, strong) DeGminoMevaSharedEntityTypeName *val$type;
@property (nonatomic, strong) DeGminoMevaSharedRequestRequestListener *val$listener;

- (void)onFinishedWithJavaUtilCollection:(id<JavaUtilCollection>)ids;
- (id)initWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)capture$0
  withDeGminoMevaSharedRequestRequestListener:(DeGminoMevaSharedRequestRequestListener *)capture$1;
@end
