//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/request/QueryMapBySubdomain.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/issuemap/ios/request/QueryMapBySubdomain.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoIssuemapIosRequestQueryMapBySubdomain

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithNSString:(NSString *)subdomain {
  return [super initWithNSString:subdomain];
}

@end
