//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityQuery.java
//
//  Created by lena on 24.06.13.
//

@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "de/gmino/meva/shared/Value.h"

@protocol DeGminoMevaSharedEntityQuery < DeGminoMevaSharedValue, NSObject >
- (id<JavaUtilCollection>)evaluate;
- (NSString *)getUrlPostfix;
@end
