//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/Entity.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoMevaSharedEntityTypeName;
@class JavaLangStringBuilder;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "java/lang/Comparable.h"

@protocol DeGminoMevaSharedEntity < JavaLangComparable, NSObject >
- (void)serializeJsonWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb;
- (void)serializeJsonWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb
                                  withNSString:(NSString *)indentation;
- (void)deserializeJsonWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (long long int)getId;
- (void)setIdWithLongInt:(long long int)id_;
- (NSString *)description;
- (NSString *)getTypeName;
- (BOOL)isReady;
- (void)reassignRelationWithNSString:(NSString *)relname
         withDeGminoMevaSharedEntity:(id<DeGminoMevaSharedEntity>)e;
- (NSString *)toShortString;
- (DeGminoMevaSharedEntityTypeName *)getType;
@end
