//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityFactory.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoMevaSharedEntityTypeName;
@protocol DeGminoMevaSharedEntity;
@protocol DeGminoMevaSharedEntityFactoryInterface;
@protocol JavaUtilCollection;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface DeGminoMevaSharedEntityFactory : NSObject {
}

+ (id<DeGminoMevaSharedEntityFactoryInterface>)factoryImplementation;
+ (void)setFactoryImplementation:(id<DeGminoMevaSharedEntityFactoryInterface>)factoryImplementation;
+ (id<JavaUtilMap>)entityMaps;
+ (void)setEntityMaps:(id<JavaUtilMap>)entityMaps;
+ (void)registerTypeWithNSString:(NSString *)typeName;
+ (id<JavaUtilCollection>)getUnloadedEntitiesByIdWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                                              withJavaUtilCollection:(id<JavaUtilCollection>)ids;
+ (id<DeGminoMevaSharedEntity>)getUnloadedEntityByIdWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                                                                            withLongInt:(long long int)id_;
+ (void)setImplementationsWithDeGminoMevaSharedEntityFactoryInterface:(id<DeGminoMevaSharedEntityFactoryInterface>)factory;
- (id)init;
@end
