//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityNotReadyException.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/meva/shared/Entity.h"
#import "de/gmino/meva/shared/EntityNotReadyException.h"
#import "java/lang/StringBuffer.h"
#import "java/util/Collection.h"
#import "java/util/Iterator.h"

@implementation DeGminoMevaSharedEntityNotReadyException

- (id)initWithDeGminoMevaSharedEntity:(id<DeGminoMevaSharedEntity>)e {
  return [super initWithNSString:[NSString stringWithFormat:@"Entity was not ready: (%@:%qi)", [((id<DeGminoMevaSharedEntity>) NIL_CHK(e)) getTypeName], [((id<DeGminoMevaSharedEntity>) NIL_CHK(e)) getId]]];
}

- (id)initWithJavaUtilCollection:(id<JavaUtilCollection>)c {
  return [super initWithNSString:[DeGminoMevaSharedEntityNotReadyException makeTextWithJavaUtilCollection:c]];
}

+ (NSString *)makeTextWithJavaUtilCollection:(id<JavaUtilCollection>)c {
  JavaLangStringBuffer *sb = [[JavaLangStringBuffer alloc] initWithNSString:@"At least on of these entities was not ready:"];
  {
    id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [((id<JavaUtilCollection>) NIL_CHK(c)) iterator]);
    while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
      id<DeGminoMevaSharedEntity> e = ((id<DeGminoMevaSharedEntity>) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
      (void) [((JavaLangStringBuffer *) NIL_CHK(sb)) appendWithNSString:[NSString stringWithFormat:@"(%@:%qi) ", [((id<DeGminoMevaSharedEntity>) NIL_CHK(e)) getTypeName], [((id<DeGminoMevaSharedEntity>) NIL_CHK(e)) getId]]];
    }
  }
  return [((JavaLangStringBuffer *) NIL_CHK(sb)) description];
}

@end
