//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityFactoryInterface.java
//
//  Created by lena on 24.06.13.
//

@protocol DeGminoMevaSharedEntity;
@protocol JavaUtilCollection;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedEntityFactoryInterface < NSObject >
- (id<JavaUtilCollection>)createEntityObjectsWithNSString:(NSString *)typeName
                                   withJavaUtilCollection:(id<JavaUtilCollection>)ids;
- (id<DeGminoMevaSharedEntity>)createEntityObjectWithNSString:(NSString *)typeName
                                                  withLongInt:(long long int)id_;
@end
