//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityBinary.java
//
//  Created by lena on 24.06.13.
//

@class JavaIoDataInputStream;
@class JavaIoDataOutputStream;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedEntityBinary < NSObject >
- (void)deserializeBinaryWithJavaIoDataInputStream:(JavaIoDataInputStream *)dis;
- (void)serializeBinaryWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)dos;
@end
