//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityTypeName.java
//
//  Created by lena on 24.06.13.
//

@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "java/lang/Comparable.h"

@interface DeGminoMevaSharedEntityTypeName : NSObject < JavaLangComparable > {
 @public
  NSString *typeName_;
}

@property (nonatomic, copy) NSString *typeName;

+ (id<JavaUtilMap>)types;
+ (void)setTypes:(id<JavaUtilMap>)types;
- (id)initWithNSString:(NSString *)typeName;
- (NSString *)description;
+ (DeGminoMevaSharedEntityTypeName *)getByStringWithNSString:(NSString *)typeName;
- (int)compareToWithId:(DeGminoMevaSharedEntityTypeName *)that;
@end
