//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/EntityNotReadyException.java
//
//  Created by lena on 24.06.13.
//

@protocol DeGminoMevaSharedEntity;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

@interface DeGminoMevaSharedEntityNotReadyException : JavaLangRuntimeException {
}

- (id)initWithDeGminoMevaSharedEntity:(id<DeGminoMevaSharedEntity>)e;
- (id)initWithJavaUtilCollection:(id<JavaUtilCollection>)c;
+ (NSString *)makeTextWithJavaUtilCollection:(id<JavaUtilCollection>)c;
@end
