//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/Query.java
//
//  Created by lena on 24.06.13.
//

void DeGminoMevaSharedQuery_unused() {}
