//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/RelationCollection.java
//
//  Created by lena on 24.06.13.
//

@class JavaUtilTreeSet;
@protocol DeGminoMevaSharedEntity;

#import "JreEmulation.h"
#import "java/util/AbstractCollection.h"
#import "java/util/Iterator.h"

@interface DeGminoMevaSharedRelationCollection : JavaUtilAbstractCollection {
 @public
  id<DeGminoMevaSharedEntity> container_;
  NSString *relname_;
  JavaUtilTreeSet *items_;
}

@property (nonatomic, strong) id<DeGminoMevaSharedEntity> container;
@property (nonatomic, copy) NSString *relname;
@property (nonatomic, strong) JavaUtilTreeSet *items;

- (id)initWithDeGminoMevaSharedEntity:(id<DeGminoMevaSharedEntity>)container
                         withNSString:(NSString *)relname;
- (id<JavaUtilIterator>)iterator;
- (int)size;
- (BOOL)containsWithId:(id)o;
- (BOOL)addWithId:(id)e;
- (BOOL)removeWithId:(id)o;
@end

@interface DeGminoMevaSharedRelationCollection_RemoveSensitiveIterator : NSObject < JavaUtilIterator > {
 @public
  DeGminoMevaSharedRelationCollection *this$0_;
  id<JavaUtilIterator> base_;
  id<DeGminoMevaSharedEntity> lastReturned_;
}

@property (nonatomic, strong) DeGminoMevaSharedRelationCollection *this$0;
@property (nonatomic, strong) id<JavaUtilIterator> base;
@property (nonatomic, strong) id<DeGminoMevaSharedEntity> lastReturned;

- (id)initWithDeGminoMevaSharedRelationCollection:(DeGminoMevaSharedRelationCollection *)outer$
                             withJavaUtilIterator:(id<JavaUtilIterator>)base;
- (BOOL)hasNext;
- (id)next;
- (void)remove;
@end
