//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/UtilImpl.java
//
//  Created by lena on 24.06.13.
//

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedUtilImpl < NSObject >
- (NSString *)formatWithNSString:(NSString *)formatString
               withNSObjectArray:(IOSObjectArray *)arguments;
- (NSString *)getBaseUrl;
@end
