//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/Util.java
//
//  Created by lena on 24.06.13.
//

@class IOSObjectArray;
@protocol DeGminoMevaSharedUtilImpl;

#import "JreEmulation.h"

@interface DeGminoMevaSharedUtil : NSObject {
}

+ (id<DeGminoMevaSharedUtilImpl>)impl;
+ (void)setImpl:(id<DeGminoMevaSharedUtilImpl>)impl;
+ (void)setImplWithDeGminoMevaSharedUtilImpl:(id<DeGminoMevaSharedUtilImpl>)impl;
+ (NSString *)formatWithNSString:(NSString *)formatString
               withNSObjectArray:(IOSObjectArray *)arguments;
+ (NSString *)getBaseUrl;
+ (id)randomElementFromWithNSObjectArray:(IOSObjectArray *)array;
+ (NSString *)capitalizeFirstWithNSString:(NSString *)str;
+ (NSString *)escapeForJsonWithNSString:(NSString *)unescaped;
- (id)init;
@end
