//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/ValueQuery.java
//
//  Created by lena on 24.06.13.
//

@protocol JavaUtilCollection;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/meva/shared/Value.h"

@protocol DeGminoMevaSharedValueQuery < DeGminoMevaSharedValue, NSObject >
- (id<JavaUtilCollection>)evaluate;
- (NSString *)getUrlPostfix;
- (id<DeGminoMevaSharedValue>)valueFromJsonWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
@end
