//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/Value.java
//
//  Created by lena on 24.06.13.
//

@class JavaLangStringBuilder;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedValue < NSObject >
- (void)serializeJsonWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb;
- (void)serializeJsonWithJavaLangStringBuilder:(JavaLangStringBuilder *)sb
                                  withNSString:(NSString *)indentation;
- (NSString *)description;
@end
