//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/ValueQueryBinary.java
//
//  Created by lena on 24.06.13.
//

@class JavaIoDataInputStream;
@protocol DeGminoMevaSharedValue;

#import "JreEmulation.h"
#import "de/gmino/meva/shared/ValueQuery.h"

@protocol DeGminoMevaSharedValueQueryBinary < DeGminoMevaSharedValueQuery, NSObject >
- (id<DeGminoMevaSharedValue>)valueFromBinaryWithJavaIoDataInputStream:(JavaIoDataInputStream *)dis;
@end
