//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/meva/shared/ValueBinary.java
//
//  Created by lena on 24.06.13.
//

@class JavaIoDataOutputStream;

#import "JreEmulation.h"

@protocol DeGminoMevaSharedValueBinary < NSObject >
- (void)serializeBinaryWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)dos;
@end
