//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/components/MevaMarkersReadOnly.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;
@class DeGminoGeobaseSharedMapEventEnum;
@protocol DeGminoGeobaseSharedMapMapView;
@protocol DeGminoGeobaseSharedMapMarkerLayer;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/map/MapListener.h"
#import "de/gmino/meva/shared/request/RequestListener.h"

@interface DeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly : NSObject < DeGminoGeobaseSharedMapMapListener > {
 @public
  id<DeGminoGeobaseSharedMapMapView> mapView_;
  id<DeGminoGeobaseSharedMapMarkerLayer> overlay_;
}

@property (nonatomic, strong) id<DeGminoGeobaseSharedMapMapView> mapView;
@property (nonatomic, strong) id<DeGminoGeobaseSharedMapMarkerLayer> overlay;

- (id)initWithDeGminoGeobaseSharedMapMapView:(id<DeGminoGeobaseSharedMapMapView>)mapview;
- (void)loadMarkers;
- (void)onEventWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
               withDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)event;
@end

@interface DeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly_$1 : DeGminoMevaSharedRequestRequestListener {
 @public
  DeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly *this$0_;
}

@property (nonatomic, strong) DeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly *this$0;

- (void)onFinishedWithJavaUtilCollection:(id<JavaUtilCollection>)objects;
- (id)initWithDeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly:(DeGminoGeobaseSharedMapComponentsMevaMarkersReadOnly *)outer$;
@end
