//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/request/QueryGeoObject.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/LatLonRect.h"
#import "de/gmino/geobase/ios/request/QueryGeoObject.h"
#import "de/gmino/geobase/shared/domain/LatLonRect.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseIosRequestQueryGeoObject

- (id)init {
  if ((self = [super init])) {
    self.area = [[DeGminoGeobaseIosDomainLatLonRect alloc] init];
  }
  return self;
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithDeGminoGeobaseIosDomainLatLonRect:(DeGminoGeobaseIosDomainLatLonRect *)area
                                        withInt:(int)maxCount {
  return [super initWithDeGminoGeobaseIosDomainLatLonRect:(DeGminoGeobaseIosDomainLatLonRect *) area withInt:maxCount];
}

@end
