//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/Address.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/Address.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseSharedDomainAddress

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithNSString:(NSString *)recipientName
          withNSString:(NSString *)street
          withNSString:(NSString *)houseNumber
          withNSString:(NSString *)zip
          withNSString:(NSString *)city
          withNSString:(NSString *)additionalAddressLine {
  return [super initWithNSString:recipientName withNSString:street withNSString:houseNumber withNSString:zip withNSString:city withNSString:additionalAddressLine];
}

@end
