//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/Duration.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/Duration.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseSharedDomainDuration

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithLongInt:(long long int)milliseconds {
  return [super initWithLongInt:milliseconds];
}

@end
