//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/GeoObject.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainImageUrl;
@class DeGminoGeobaseSharedDomainLatLon;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/domain/gen/GeoObjectGen.h"

@interface DeGminoGeobaseSharedDomainGeoObject : DeGminoGeobaseSharedDomainGenGeoObjectGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)markerImage;
@end
