//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/GeoObject.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/GeoObject.h"
#import "de/gmino/geobase/shared/domain/ImageUrl.h"
#import "de/gmino/geobase/shared/domain/LatLon.h"

@implementation DeGminoGeobaseSharedDomainGeoObject

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *)markerImage {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *) location withNSString:title withNSString:description_ withDeGminoGeobaseSharedDomainImageUrl:(DeGminoGeobaseSharedDomainImageUrl *) markerImage])) {
    self.ready = YES;
  }
  return self;
}

@end
