//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/ImageUrl.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/ImageUrl.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseSharedDomainImageUrl

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithNSString:(NSString *)url {
  return [super initWithNSString:url];
}

@end
