//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/LatLon.java
//
//  Created by lena on 24.06.13.
//

@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/domain/gen/LatLonGen.h"

@interface DeGminoGeobaseSharedDomainLatLon : DeGminoGeobaseSharedDomainGenLatLonGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithDouble:(double)latitude
          withDouble:(double)longitude;
@end
