//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/LatLonRect.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/domain/gen/LatLonRectGen.h"

@interface DeGminoGeobaseSharedDomainLatLonRect : DeGminoGeobaseSharedDomainGenLatLonRectGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)min
          withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)max;
- (id)initWithDouble:(double)south
          withDouble:(double)west
          withDouble:(double)north
          withDouble:(double)east;
@end
