//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/LatLonRect.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/LatLon.h"
#import "de/gmino/geobase/shared/domain/LatLonRect.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseSharedDomainLatLonRect

- (id)init {
  if ((self = [super init])) {
    self.min = [[DeGminoGeobaseSharedDomainLatLon alloc] init];
    self.max = [[DeGminoGeobaseSharedDomainLatLon alloc] init];
  }
  return self;
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)min
          withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)max {
  return [super initWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *) min withDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *) max];
}

- (id)initWithDouble:(double)south
          withDouble:(double)west
          withDouble:(double)north
          withDouble:(double)east {
  if ((self = [super init])) {
    self.min = [[DeGminoGeobaseSharedDomainLatLon alloc] initWithDouble:south withDouble:west];
    self.max = [[DeGminoGeobaseSharedDomainLatLon alloc] initWithDouble:north withDouble:east];
  }
  return self;
}

@end
