//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/Poi.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;

#import "JreEmulation.h"
#import "de/gmino/meva/shared/Entity.h"

@protocol DeGminoGeobaseSharedDomainPoi < DeGminoMevaSharedEntity, NSObject >
- (DeGminoGeobaseSharedDomainLatLon *)getLocation;
- (NSString *)getTitle;
- (NSString *)getDescription;
@end
