//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/Timestamp.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/Duration.h"
#import "de/gmino/geobase/shared/domain/Timestamp.h"
#import "java/lang/System.h"
#import "java/util/Date.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseSharedDomainTimestamp

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithLongInt:(long long int)millisSinceEpoch {
  return [super initWithLongInt:millisSinceEpoch];
}

- (JavaUtilDate *)toDate {
  return [[JavaUtilDate alloc] initWithLongInt:millisSinceEpoch_];
}

- (DeGminoGeobaseSharedDomainTimestamp *)addDurationWithDeGminoGeobaseSharedDomainDuration:(DeGminoGeobaseSharedDomainDuration *)d {
  return [[DeGminoGeobaseSharedDomainTimestamp alloc] initWithLongInt:millisSinceEpoch_ + [((DeGminoGeobaseSharedDomainDuration *) NIL_CHK(d)) getMilliseconds]];
}

+ (DeGminoGeobaseSharedDomainTimestamp *)now {
  return [[DeGminoGeobaseSharedDomainTimestamp alloc] initWithLongInt:[JavaLangSystem currentTimeMillis]];
}

- (DeGminoGeobaseSharedDomainDuration *)timeUntilWithDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)then {
  return [[DeGminoGeobaseSharedDomainDuration alloc] initWithLongInt:[((DeGminoGeobaseSharedDomainTimestamp *) NIL_CHK(then)) getMillisSinceEpoch] - millisSinceEpoch_];
}

@end
