//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/domain/Timestamp.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainDuration;
@class JavaUtilDate;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/domain/gen/TimestampGen.h"

@interface DeGminoGeobaseSharedDomainTimestamp : DeGminoGeobaseSharedDomainGenTimestampGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithLongInt:(long long int)millisSinceEpoch;
- (JavaUtilDate *)toDate;
- (DeGminoGeobaseSharedDomainTimestamp *)addDurationWithDeGminoGeobaseSharedDomainDuration:(DeGminoGeobaseSharedDomainDuration *)d;
+ (DeGminoGeobaseSharedDomainTimestamp *)now;
- (DeGminoGeobaseSharedDomainDuration *)timeUntilWithDeGminoGeobaseSharedDomainTimestamp:(DeGminoGeobaseSharedDomainTimestamp *)then;
@end
