//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/Distance.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/Distance.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseIosDomainDistance

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithDouble:(double)meters {
  return [super initWithDouble:meters];
}

@end
