//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/Duration.java
//
//  Created by lena on 24.06.13.
//

@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/ios/domain/gen/DurationGen.h"

@interface DeGminoGeobaseIosDomainDuration : DeGminoGeobaseIosDomainGenDurationGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithLongInt:(long long int)milliseconds;
@end
