//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/GeoObject.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/GeoObject.h"
#import "de/gmino/geobase/ios/domain/ImageUrl.h"
#import "de/gmino/geobase/ios/domain/LatLon.h"

@implementation DeGminoGeobaseIosDomainGeoObject

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoGeobaseIosDomainImageUrl:(DeGminoGeobaseIosDomainImageUrl *)markerImage {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *) location withNSString:title withNSString:description_ withDeGminoGeobaseIosDomainImageUrl:(DeGminoGeobaseIosDomainImageUrl *) markerImage])) {
    self.ready = YES;
  }
  return self;
}

@end
