//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/ImageUrl.java
//
//  Created by lena on 24.06.13.
//

@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/ios/domain/gen/ImageUrlGen.h"

@interface DeGminoGeobaseIosDomainImageUrl : DeGminoGeobaseIosDomainGenImageUrlGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithNSString:(NSString *)url;
@end
