//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/LatLon.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/LatLon.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseIosDomainLatLon

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithDouble:(double)latitude
          withDouble:(double)longitude {
  return [super initWithDouble:latitude withDouble:longitude];
}

@end
