//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/LatLonRect.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/LatLon.h"
#import "de/gmino/geobase/ios/domain/LatLonRect.h"
#import "de/gmino/geobase/shared/domain/LatLon.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseIosDomainLatLonRect

- (id)init {
  if ((self = [super init])) {
    self.min = [[DeGminoGeobaseIosDomainLatLon alloc] init];
    self.max = [[DeGminoGeobaseIosDomainLatLon alloc] init];
  }
  return self;
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)min
          withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)max {
  return [super initWithDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *) min withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *) max];
}

@end
