//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/LatLonRect.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseIosDomainLatLon;
@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/geobase/ios/domain/gen/LatLonRectGen.h"

@interface DeGminoGeobaseIosDomainLatLonRect : DeGminoGeobaseIosDomainGenLatLonRectGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)min
          withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)max;
@end
