//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/ios/domain/Timestamp.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/Timestamp.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoGeobaseIosDomainTimestamp

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithLongInt:(long long int)millisSinceEpoch {
  return [super initWithLongInt:millisSinceEpoch];
}

@end
