//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/Comment.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/Timestamp.h"
#import "de/gmino/issuemap/ios/domain/Comment.h"
#import "de/gmino/issuemap/ios/domain/Issue.h"

@implementation DeGminoIssuemapIosDomainComment

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapIosDomainIssue:(DeGminoIssuemapIosDomainIssue *)issue
         withNSString:(NSString *)text
         withNSString:(NSString *)user
withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *)timestamp
             withBOOL:(BOOL)deleted {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoIssuemapIosDomainIssue:(DeGminoIssuemapIosDomainIssue *) issue withNSString:text withNSString:user withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *) timestamp withBOOL:deleted])) {
    self.ready = YES;
  }
  return self;
}

@end
