//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/Issue.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/ios/domain/ImageUrl.h"
#import "de/gmino/geobase/ios/domain/LatLon.h"
#import "de/gmino/geobase/ios/domain/Timestamp.h"
#import "de/gmino/issuemap/ios/domain/Issue.h"
#import "de/gmino/issuemap/ios/domain/Map.h"
#import "de/gmino/issuemap/ios/domain/Markertype.h"

@implementation DeGminoIssuemapIosDomainIssue

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *)location
         withNSString:(NSString *)title
         withNSString:(NSString *)description_
withDeGminoIssuemapIosDomainMarkertype:(DeGminoIssuemapIosDomainMarkertype *)markertype
withDeGminoIssuemapIosDomainMap:(DeGminoIssuemapIosDomainMap *)map_instance
withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *)creationTimestamp
              withInt:(int)rating
              withInt:(int)number_of_rating
             withBOOL:(BOOL)resolved
             withBOOL:(BOOL)deleted
withDeGminoGeobaseIosDomainImageUrl:(DeGminoGeobaseIosDomainImageUrl *)primary_picture
withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *)eventTimestamp
           withDouble:(double)price
         withNSString:(NSString *)organizer
         withNSString:(NSString *)email
         withNSString:(NSString *)phone {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoGeobaseIosDomainLatLon:(DeGminoGeobaseIosDomainLatLon *) location withNSString:title withNSString:description_ withDeGminoIssuemapIosDomainMarkertype:(DeGminoIssuemapIosDomainMarkertype *) markertype withDeGminoIssuemapIosDomainMap:(DeGminoIssuemapIosDomainMap *) map_instance withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *) creationTimestamp withInt:rating withInt:number_of_rating withBOOL:resolved withBOOL:deleted withDeGminoGeobaseIosDomainImageUrl:(DeGminoGeobaseIosDomainImageUrl *) primary_picture withDeGminoGeobaseIosDomainTimestamp:(DeGminoGeobaseIosDomainTimestamp *) eventTimestamp withDouble:price withNSString:organizer withNSString:email withNSString:phone])) {
    self.ready = YES;
  }
  return self;
}

@end
