//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/MapHasMarkertype.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoIssuemapIosDomainMap;
@class DeGminoIssuemapIosDomainMarkertype;

#import "JreEmulation.h"
#import "de/gmino/issuemap/ios/domain/gen/MapHasMarkertypeGen.h"

@interface DeGminoIssuemapIosDomainMapHasMarkertype : DeGminoIssuemapIosDomainGenMapHasMarkertypeGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapIosDomainMarkertype:(DeGminoIssuemapIosDomainMarkertype *)markertype
withDeGminoIssuemapIosDomainMap:(DeGminoIssuemapIosDomainMap *)map;
@end
