//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/MapHasMarkertype.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/issuemap/ios/domain/Map.h"
#import "de/gmino/issuemap/ios/domain/MapHasMarkertype.h"
#import "de/gmino/issuemap/ios/domain/Markertype.h"

@implementation DeGminoIssuemapIosDomainMapHasMarkertype

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
withDeGminoIssuemapIosDomainMarkertype:(DeGminoIssuemapIosDomainMarkertype *)markertype
withDeGminoIssuemapIosDomainMap:(DeGminoIssuemapIosDomainMap *)map {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withDeGminoIssuemapIosDomainMarkertype:(DeGminoIssuemapIosDomainMarkertype *) markertype withDeGminoIssuemapIosDomainMap:(DeGminoIssuemapIosDomainMap *) map])) {
    self.ready = YES;
  }
  return self;
}

@end
