//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/Markertype.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/issuemap/ios/domain/Markertype.h"

@implementation DeGminoIssuemapIosDomainMarkertype

- (id)initWithLongInt:(long long int)id_ {
  return [super initWithLongInt:id_];
}

- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
         withNSString:(NSString *)markerName
         withNSString:(NSString *)imageName
              withInt:(int)imageWidth
              withInt:(int)imageHeight {
  if ((self = [super initWithLongInt:id_ withBOOL:ready withNSString:markerName withNSString:imageName withInt:imageWidth withInt:imageHeight])) {
    self.ready = YES;
  }
  return self;
}

@end
