//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/src/de/gmino/issuemap/ios/domain/Markertype.java
//
//  Created by lena on 24.06.13.
//

#import "JreEmulation.h"
#import "de/gmino/issuemap/ios/domain/gen/MarkertypeGen.h"

@interface DeGminoIssuemapIosDomainMarkertype : DeGminoIssuemapIosDomainGenMarkertypeGen {
}

- (id)initWithLongInt:(long long int)id_;
- (id)initWithLongInt:(long long int)id_
             withBOOL:(BOOL)ready
         withNSString:(NSString *)markerName
         withNSString:(NSString *)imageName
              withInt:(int)imageWidth
              withInt:(int)imageHeight;
@end
