//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/request/QueryIssuesByMap.java
//
//  Created by lena on 24.06.13.
//

@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/request/gen/QueryIssuesByMapGen.h"

@interface DeGminoIssuemapSharedRequestQueryIssuesByMap : DeGminoIssuemapSharedRequestGenQueryIssuesByMapGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithLongInt:(long long int)map_instance;
@end
