//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/request/QueryMapBySubdomain.java
//
//  Created by lena on 24.06.13.
//

@protocol OrgItemscriptCoreValuesJsonObject;

#import "JreEmulation.h"
#import "de/gmino/issuemap/shared/request/gen/QueryMapBySubdomainGen.h"

@interface DeGminoIssuemapSharedRequestQueryMapBySubdomain : DeGminoIssuemapSharedRequestGenQueryMapBySubdomainGen {
}

- (id)init;
- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json;
- (id)initWithNSString:(NSString *)subdomain;
@end
