//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/issuemap/shared/request/QueryIssuesByMap.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/issuemap/shared/request/QueryIssuesByMap.h"
#import "org/itemscript/core/values/JsonObject.h"

@implementation DeGminoIssuemapSharedRequestQueryIssuesByMap

- (id)init {
  return [super init];
}

- (id)initWithOrgItemscriptCoreValuesJsonObject:(id<OrgItemscriptCoreValuesJsonObject>)json {
  return [super initWithOrgItemscriptCoreValuesJsonObject:json];
}

- (id)initWithLongInt:(long long int)map_instance {
  return [super initWithLongInt:map_instance];
}

@end
