//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/AbstractMapView.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;
@class DeGminoGeobaseSharedDomainLatLonRect;
@class DeGminoGeobaseSharedMapEventEnum;
@class DeGminoGeobaseSharedMapMapProviderEnum;
@protocol DeGminoGeobaseSharedMapMapLayer;
@protocol DeGminoGeobaseSharedMapMapListener;
@protocol DeGminoGeobaseSharedMapMarkerLayer;
@protocol DeGminoGeobaseSharedMapSmartLayer;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#import "de/gmino/geobase/shared/map/MapView.h"

@interface DeGminoGeobaseSharedMapAbstractMapView : NSObject < DeGminoGeobaseSharedMapMapView > {
 @public
  id<JavaUtilMap> eventListeners_;
}

@property (nonatomic, strong) id<JavaUtilMap> eventListeners;

- (id)init;
- (void)handleEventWithDouble:(double)lat
                   withDouble:(double)lon
withDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)type;
- (void)addEventListenerWithDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)event
                      withDeGminoGeobaseSharedMapMapListener:(id<DeGminoGeobaseSharedMapMapListener>)listener;
- (void)setCenterAndZoomWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)center
                                                  withDouble:(double)zoom
                                                    withBOOL:(BOOL)animate;
- (void)addLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)param0;
- (DeGminoGeobaseSharedDomainLatLon *)getCenter;
- (double)getMaxZoom;
- (double)getMinZoom;
- (DeGminoGeobaseSharedDomainLatLonRect *)getVisibleArea;
- (double)getZoom;
- (id<DeGminoGeobaseSharedMapMapLayer>)newMapLayerWithDeGminoGeobaseSharedMapMapProviderEnum:(DeGminoGeobaseSharedMapMapProviderEnum *)param0 OBJC_METHOD_FAMILY_NONE;
- (id<DeGminoGeobaseSharedMapMarkerLayer>)newMarkerLayerWithNSString:(NSString *)param0 OBJC_METHOD_FAMILY_NONE;
- (id<DeGminoGeobaseSharedMapSmartLayer>)newSmartLayerWithNSString:(NSString *)param0 OBJC_METHOD_FAMILY_NONE;
- (void)removeLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)param0;
- (void)setCenterWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)param0
                                             withBOOL:(BOOL)param1;
- (void)setZoomWithDouble:(double)param0;
- (BOOL)supportsFreeZoom;
@end
