//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/AbstractMapView.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/domain/LatLon.h"
#import "de/gmino/geobase/shared/domain/LatLonRect.h"
#import "de/gmino/geobase/shared/map/AbstractMapView.h"
#import "de/gmino/geobase/shared/map/Event.h"
#import "de/gmino/geobase/shared/map/MapLayer.h"
#import "de/gmino/geobase/shared/map/MapListener.h"
#import "de/gmino/geobase/shared/map/MapProvider.h"
#import "de/gmino/geobase/shared/map/MapView.h"
#import "de/gmino/geobase/shared/map/MarkerLayer.h"
#import "de/gmino/geobase/shared/map/SmartLayer.h"
#import "java/util/Collection.h"
#import "java/util/Iterator.h"
#import "java/util/LinkedList.h"
#import "java/util/Map.h"
#import "java/util/TreeMap.h"

@implementation DeGminoGeobaseSharedMapAbstractMapView

@synthesize eventListeners = eventListeners_;

- (id)init {
  if ((self = [super init])) {
    eventListeners_ = [[JavaUtilTreeMap alloc] init];
  }
  return self;
}

- (void)handleEventWithDouble:(double)lat
                   withDouble:(double)lon
withDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)type {
  id<JavaUtilCollection> listeners = ((id<JavaUtilCollection>) [((id<JavaUtilMap>) NIL_CHK(eventListeners_)) getWithId:type]);
  if (listeners != nil) {
    DeGminoGeobaseSharedDomainLatLon *location = [[DeGminoGeobaseSharedDomainLatLon alloc] initWithDouble:lat withDouble:lon];
    {
      id<JavaUtilIterator> iter__ = ((id<JavaUtilIterator>) [listeners iterator]);
      while ([((id<JavaUtilIterator>) NIL_CHK(iter__)) hasNext]) {
        id<DeGminoGeobaseSharedMapMapListener> listener = ((id<DeGminoGeobaseSharedMapMapListener>) [((id<JavaUtilIterator>) NIL_CHK(iter__)) next]);
        [((id<DeGminoGeobaseSharedMapMapListener>) NIL_CHK(listener)) onEventWithDeGminoGeobaseSharedDomainLatLon:location withDeGminoGeobaseSharedMapEventEnum:type];
      }
    }
  }
}

- (void)addEventListenerWithDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)event
                      withDeGminoGeobaseSharedMapMapListener:(id<DeGminoGeobaseSharedMapMapListener>)listener {
  id<JavaUtilCollection> listeners = ((id<JavaUtilCollection>) [((id<JavaUtilMap>) NIL_CHK(eventListeners_)) getWithId:event]);
  if (listeners == nil) {
    listeners = [[JavaUtilLinkedList alloc] init];
    (void) [((id<JavaUtilMap>) NIL_CHK(eventListeners_)) putWithId:event withId:listeners];
  }
  [((id<JavaUtilCollection>) NIL_CHK(listeners)) addWithId:listener];
}

- (void)setCenterAndZoomWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)center
                                                  withDouble:(double)zoom
                                                    withBOOL:(BOOL)animate {
  [self setCenterWithDeGminoGeobaseSharedDomainLatLon:center withBOOL:animate];
  [self setZoomWithDouble:zoom];
}

- (void)addLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (DeGminoGeobaseSharedDomainLatLon *)getCenter {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)getMaxZoom {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)getMinZoom {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (DeGminoGeobaseSharedDomainLatLonRect *)getVisibleArea {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (double)getZoom {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<DeGminoGeobaseSharedMapMapLayer>)newMapLayerWithDeGminoGeobaseSharedMapMapProviderEnum:(DeGminoGeobaseSharedMapMapProviderEnum *)param0 OBJC_METHOD_FAMILY_NONE {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<DeGminoGeobaseSharedMapMarkerLayer>)newMarkerLayerWithNSString:(NSString *)param0 OBJC_METHOD_FAMILY_NONE {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (id<DeGminoGeobaseSharedMapSmartLayer>)newSmartLayerWithNSString:(NSString *)param0 OBJC_METHOD_FAMILY_NONE {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)removeLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)setCenterWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)param0
                                             withBOOL:(BOOL)param1 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)setZoomWithDouble:(double)param0 {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (BOOL)supportsFreeZoom {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)copyAllPropertiesTo:(id)copy {
  [super copyAllPropertiesTo:copy];
  DeGminoGeobaseSharedMapAbstractMapView *typedCopy = (DeGminoGeobaseSharedMapAbstractMapView *) copy;
  typedCopy.eventListeners = eventListeners_;
}

@end
