//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/Event.java
//
//  Created by lena on 24.06.13.
//

#import "JreEmulation.h"
#import "java/lang/Enum.h"

typedef enum {
  DeGminoGeobaseSharedMapEvent_mouseover = 0,
  DeGminoGeobaseSharedMapEvent_mouseout = 1,
  DeGminoGeobaseSharedMapEvent_mousedown = 2,
  DeGminoGeobaseSharedMapEvent_mouseup = 3,
  DeGminoGeobaseSharedMapEvent_mousemove = 4,
  DeGminoGeobaseSharedMapEvent_click = 5,
  DeGminoGeobaseSharedMapEvent_dblclick = 6,
  DeGminoGeobaseSharedMapEvent_rightclick = 7,
  DeGminoGeobaseSharedMapEvent_dblrightclick = 8,
  DeGminoGeobaseSharedMapEvent_resize = 9,
  DeGminoGeobaseSharedMapEvent_focus = 10,
  DeGminoGeobaseSharedMapEvent_blur = 11,
  DeGminoGeobaseSharedMapEvent_touchstart = 12,
  DeGminoGeobaseSharedMapEvent_touchmove = 13,
  DeGminoGeobaseSharedMapEvent_touchend = 14,
  DeGminoGeobaseSharedMapEvent_keydown = 15,
  DeGminoGeobaseSharedMapEvent_move = 16,
  DeGminoGeobaseSharedMapEvent_zoom = 17,
} DeGminoGeobaseSharedMapEvent;

@interface DeGminoGeobaseSharedMapEventEnum : JavaLangEnum < NSCopying > {
 @public
  BOOL changesView_;
}
@property (nonatomic, assign) BOOL changesView;

+ (DeGminoGeobaseSharedMapEventEnum *)mouseover;
+ (DeGminoGeobaseSharedMapEventEnum *)mouseout;
+ (DeGminoGeobaseSharedMapEventEnum *)mousedown;
+ (DeGminoGeobaseSharedMapEventEnum *)mouseup;
+ (DeGminoGeobaseSharedMapEventEnum *)mousemove;
+ (DeGminoGeobaseSharedMapEventEnum *)click;
+ (DeGminoGeobaseSharedMapEventEnum *)dblclick;
+ (DeGminoGeobaseSharedMapEventEnum *)rightclick;
+ (DeGminoGeobaseSharedMapEventEnum *)dblrightclick;
+ (DeGminoGeobaseSharedMapEventEnum *)resize;
+ (DeGminoGeobaseSharedMapEventEnum *)focus;
+ (DeGminoGeobaseSharedMapEventEnum *)blur;
+ (DeGminoGeobaseSharedMapEventEnum *)touchstart;
+ (DeGminoGeobaseSharedMapEventEnum *)touchmove;
+ (DeGminoGeobaseSharedMapEventEnum *)touchend;
+ (DeGminoGeobaseSharedMapEventEnum *)keydown;
+ (DeGminoGeobaseSharedMapEventEnum *)move;
+ (DeGminoGeobaseSharedMapEventEnum *)zoom;
+ (IOSObjectArray *)values;
+ (DeGminoGeobaseSharedMapEventEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (id)initWithBOOL:(BOOL)changesView
      withNSString:(NSString *)name
           withInt:(int)ordinal;
- (id)initWithNSString:(NSString *)name withInt:(int)ordinal;
- (BOOL)isChangingView;
@end
