//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/Event.java
//
//  Created by lena on 24.06.13.
//

#import "de/gmino/geobase/shared/map/Event.h"
#import "java/lang/IllegalArgumentException.h"


static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_mouseover;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_mouseout;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_mousedown;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_mouseup;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_mousemove;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_click;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_dblclick;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_rightclick;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_dblrightclick;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_resize;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_focus;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_blur;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_touchstart;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_touchmove;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_touchend;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_keydown;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_move;
static DeGminoGeobaseSharedMapEventEnum *DeGminoGeobaseSharedMapEventEnum_zoom;
IOSObjectArray *DeGminoGeobaseSharedMapEventEnum_values;

@implementation DeGminoGeobaseSharedMapEventEnum

+ (DeGminoGeobaseSharedMapEventEnum *)mouseover {
  return DeGminoGeobaseSharedMapEventEnum_mouseover;
}
+ (DeGminoGeobaseSharedMapEventEnum *)mouseout {
  return DeGminoGeobaseSharedMapEventEnum_mouseout;
}
+ (DeGminoGeobaseSharedMapEventEnum *)mousedown {
  return DeGminoGeobaseSharedMapEventEnum_mousedown;
}
+ (DeGminoGeobaseSharedMapEventEnum *)mouseup {
  return DeGminoGeobaseSharedMapEventEnum_mouseup;
}
+ (DeGminoGeobaseSharedMapEventEnum *)mousemove {
  return DeGminoGeobaseSharedMapEventEnum_mousemove;
}
+ (DeGminoGeobaseSharedMapEventEnum *)click {
  return DeGminoGeobaseSharedMapEventEnum_click;
}
+ (DeGminoGeobaseSharedMapEventEnum *)dblclick {
  return DeGminoGeobaseSharedMapEventEnum_dblclick;
}
+ (DeGminoGeobaseSharedMapEventEnum *)rightclick {
  return DeGminoGeobaseSharedMapEventEnum_rightclick;
}
+ (DeGminoGeobaseSharedMapEventEnum *)dblrightclick {
  return DeGminoGeobaseSharedMapEventEnum_dblrightclick;
}
+ (DeGminoGeobaseSharedMapEventEnum *)resize {
  return DeGminoGeobaseSharedMapEventEnum_resize;
}
+ (DeGminoGeobaseSharedMapEventEnum *)focus {
  return DeGminoGeobaseSharedMapEventEnum_focus;
}
+ (DeGminoGeobaseSharedMapEventEnum *)blur {
  return DeGminoGeobaseSharedMapEventEnum_blur;
}
+ (DeGminoGeobaseSharedMapEventEnum *)touchstart {
  return DeGminoGeobaseSharedMapEventEnum_touchstart;
}
+ (DeGminoGeobaseSharedMapEventEnum *)touchmove {
  return DeGminoGeobaseSharedMapEventEnum_touchmove;
}
+ (DeGminoGeobaseSharedMapEventEnum *)touchend {
  return DeGminoGeobaseSharedMapEventEnum_touchend;
}
+ (DeGminoGeobaseSharedMapEventEnum *)keydown {
  return DeGminoGeobaseSharedMapEventEnum_keydown;
}
+ (DeGminoGeobaseSharedMapEventEnum *)move {
  return DeGminoGeobaseSharedMapEventEnum_move;
}
+ (DeGminoGeobaseSharedMapEventEnum *)zoom {
  return DeGminoGeobaseSharedMapEventEnum_zoom;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

@synthesize changesView = changesView_;

- (id)initWithBOOL:(BOOL)changesView
      withNSString:(NSString *)name
           withInt:(int)ordinal {
  if ((self = [super initWithNSString:name withInt:ordinal])) {
    self.changesView = changesView;
  }
  return self;
}

- (id)initWithNSString:(NSString *)name withInt:(int)ordinal {
  if ((self = [super initWithNSString:name withInt:ordinal])) {
    self.changesView = NO;
  }
  return self;
}

- (BOOL)isChangingView {
  return changesView_;
}

+ (void)initialize {
  if (self == [DeGminoGeobaseSharedMapEventEnum class]) {
    DeGminoGeobaseSharedMapEventEnum_mouseover = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"mouseover" withInt:0];
    DeGminoGeobaseSharedMapEventEnum_mouseout = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"mouseout" withInt:1];
    DeGminoGeobaseSharedMapEventEnum_mousedown = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"mousedown" withInt:2];
    DeGminoGeobaseSharedMapEventEnum_mouseup = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"mouseup" withInt:3];
    DeGminoGeobaseSharedMapEventEnum_mousemove = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"mousemove" withInt:4];
    DeGminoGeobaseSharedMapEventEnum_click = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"click" withInt:5];
    DeGminoGeobaseSharedMapEventEnum_dblclick = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"dblclick" withInt:6];
    DeGminoGeobaseSharedMapEventEnum_rightclick = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"rightclick" withInt:7];
    DeGminoGeobaseSharedMapEventEnum_dblrightclick = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"dblrightclick" withInt:8];
    DeGminoGeobaseSharedMapEventEnum_resize = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"resize" withInt:9];
    DeGminoGeobaseSharedMapEventEnum_focus = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"focus" withInt:10];
    DeGminoGeobaseSharedMapEventEnum_blur = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"blur" withInt:11];
    DeGminoGeobaseSharedMapEventEnum_touchstart = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"touchstart" withInt:12];
    DeGminoGeobaseSharedMapEventEnum_touchmove = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"touchmove" withInt:13];
    DeGminoGeobaseSharedMapEventEnum_touchend = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"touchend" withInt:14];
    DeGminoGeobaseSharedMapEventEnum_keydown = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithNSString:@"keydown" withInt:15];
    DeGminoGeobaseSharedMapEventEnum_move = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithBOOL:YES withNSString:@"DeGminoGeobaseSharedMapEvent_move" withInt:16];
    DeGminoGeobaseSharedMapEventEnum_zoom = [[DeGminoGeobaseSharedMapEventEnum alloc] initWithBOOL:YES withNSString:@"DeGminoGeobaseSharedMapEvent_zoom" withInt:17];
    DeGminoGeobaseSharedMapEventEnum_values = [[IOSObjectArray alloc] initWithObjects:(id[]){ DeGminoGeobaseSharedMapEventEnum_mouseover, DeGminoGeobaseSharedMapEventEnum_mouseout, DeGminoGeobaseSharedMapEventEnum_mousedown, DeGminoGeobaseSharedMapEventEnum_mouseup, DeGminoGeobaseSharedMapEventEnum_mousemove, DeGminoGeobaseSharedMapEventEnum_click, DeGminoGeobaseSharedMapEventEnum_dblclick, DeGminoGeobaseSharedMapEventEnum_rightclick, DeGminoGeobaseSharedMapEventEnum_dblrightclick, DeGminoGeobaseSharedMapEventEnum_resize, DeGminoGeobaseSharedMapEventEnum_focus, DeGminoGeobaseSharedMapEventEnum_blur, DeGminoGeobaseSharedMapEventEnum_touchstart, DeGminoGeobaseSharedMapEventEnum_touchmove, DeGminoGeobaseSharedMapEventEnum_touchend, DeGminoGeobaseSharedMapEventEnum_keydown, DeGminoGeobaseSharedMapEventEnum_move, DeGminoGeobaseSharedMapEventEnum_zoom, nil } count:18 type:[IOSClass classWithClass:[DeGminoGeobaseSharedMapEventEnum class]]];
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithArray:DeGminoGeobaseSharedMapEventEnum_values];
}

+ (DeGminoGeobaseSharedMapEventEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < [DeGminoGeobaseSharedMapEventEnum_values count]; i++) {
    DeGminoGeobaseSharedMapEventEnum *e = [DeGminoGeobaseSharedMapEventEnum_values objectAtIndex:i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

@end
