//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/Hasher.java
//
//  Created by lena on 24.06.13.
//

#import "JreEmulation.h"

@interface DeGminoGeobaseSharedMapHasher : NSObject {
 @public
  int hash__;
}

@property (nonatomic, assign) int hash_;

- (void)hashIntWithInt:(int)i;
- (void)hashLongWithLongInt:(long long int)l;
- (void)hashCharWithUnichar:(unichar)c;
- (void)hashShortWithShortInt:(short int)s;
- (void)hashObjectWithId:(id)o;
- (void)hashFloatWithFloat:(float)f;
- (void)hashDoubleWithDouble:(double)d;
- (void)hashBooleanWithBOOL:(BOOL)b;
- (int)getValue;
- (void)reset;
- (id)init;
@end
