//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/IconRenderer.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedMapHasher;
@protocol DeGminoGeobaseSharedDomainPoi;

#import "JreEmulation.h"

@protocol DeGminoGeobaseSharedMapIconRenderer < NSObject >
- (void)getIconHashWithDeGminoGeobaseSharedMapHasher:(DeGminoGeobaseSharedMapHasher *)hash_
                                              withId:(id<DeGminoGeobaseSharedDomainPoi>)object;
- (void)renderIconWithId:(id)con
                  withId:(id<DeGminoGeobaseSharedDomainPoi>)object;
@end
