//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/MapListener.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;
@class DeGminoGeobaseSharedMapEventEnum;

#import "JreEmulation.h"

@protocol DeGminoGeobaseSharedMapMapListener < NSObject >
- (void)onEventWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location
               withDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)event;
@end
