//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/MapLayer.java
//
//  Created by lena on 24.06.13.
//

#import "JreEmulation.h"

@protocol DeGminoGeobaseSharedMapMapLayer < NSObject >
- (NSString *)getName;
- (double)getMinZoom;
- (double)getMaxZoom;
- (NSString *)getLicenseText;
- (void)setVisibilityWithBOOL:(BOOL)visible;
- (void)setOpacityWithDouble:(double)opacity;
@end
