//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/MapProvider.java
//
//  Created by lena on 24.06.13.
//

#import "JreEmulation.h"
#import "java/lang/Enum.h"

typedef enum {
  DeGminoGeobaseSharedMapMapProvider_MAPNIK = 0,
  DeGminoGeobaseSharedMapMapProvider_OPEN_CYCLE_MAP = 1,
  DeGminoGeobaseSharedMapMapProvider_MAPQUEST = 2,
  DeGminoGeobaseSharedMapMapProvider_MAPQUEST_AERIAL = 3,
  DeGminoGeobaseSharedMapMapProvider_TRANSPORT = 4,
  DeGminoGeobaseSharedMapMapProvider_LANDSCAPE = 5,
  DeGminoGeobaseSharedMapMapProvider_NO_LABELS = 6,
  DeGminoGeobaseSharedMapMapProvider_HIKE_BIKE = 7,
  DeGminoGeobaseSharedMapMapProvider_OPEN_STREET_BROWSER = 8,
  DeGminoGeobaseSharedMapMapProvider_OE_P_N_V = 9,
  DeGminoGeobaseSharedMapMapProvider_WANDER_REIT = 10,
} DeGminoGeobaseSharedMapMapProvider;

@interface DeGminoGeobaseSharedMapMapProviderEnum : JavaLangEnum < NSCopying > {
 @public
  NSString *urlName_;
  NSString *readableName_;
}
@property (nonatomic, copy) NSString *urlName;
@property (nonatomic, copy) NSString *readableName;

+ (DeGminoGeobaseSharedMapMapProviderEnum *)MAPNIK;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)OPEN_CYCLE_MAP;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)MAPQUEST;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)MAPQUEST_AERIAL;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)TRANSPORT;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)LANDSCAPE;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)NO_LABELS;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)HIKE_BIKE;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)OPEN_STREET_BROWSER;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)OE_P_N_V;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)WANDER_REIT;
+ (IOSObjectArray *)values;
+ (DeGminoGeobaseSharedMapMapProviderEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;
- (NSString *)getUrlName;
- (NSString *)getReadableName;
- (id)initWithNSString:(NSString *)urlName
          withNSString:(NSString *)readableName
          withNSString:(NSString *)name
               withInt:(int)ordinal;
@end
