//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/MapView.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainLatLon;
@class DeGminoGeobaseSharedDomainLatLonRect;
@class DeGminoGeobaseSharedMapEventEnum;
@class DeGminoGeobaseSharedMapMapProviderEnum;
@protocol DeGminoGeobaseSharedMapMapLayer;
@protocol DeGminoGeobaseSharedMapMapListener;
@protocol DeGminoGeobaseSharedMapMarkerLayer;
@protocol DeGminoGeobaseSharedMapSmartLayer;

#import "JreEmulation.h"

@protocol DeGminoGeobaseSharedMapMapView < NSObject >
- (DeGminoGeobaseSharedDomainLatLon *)getCenter;
- (DeGminoGeobaseSharedDomainLatLonRect *)getVisibleArea;
- (void)setCenterWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)center
                                             withBOOL:(BOOL)animate;
- (void)setCenterAndZoomWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)center
                                                  withDouble:(double)zoom
                                                    withBOOL:(BOOL)animate;
- (void)setZoomWithDouble:(double)zoom;
- (double)getMinZoom;
- (double)getMaxZoom;
- (double)getZoom;
- (BOOL)supportsFreeZoom;
- (void)addLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)layer;
- (void)removeLayerWithDeGminoGeobaseSharedMapMapLayer:(id<DeGminoGeobaseSharedMapMapLayer>)layer;
- (void)addEventListenerWithDeGminoGeobaseSharedMapEventEnum:(DeGminoGeobaseSharedMapEventEnum *)event
                      withDeGminoGeobaseSharedMapMapListener:(id<DeGminoGeobaseSharedMapMapListener>)listener;
- (id<DeGminoGeobaseSharedMapMarkerLayer>)newMarkerLayerWithNSString:(NSString *)name OBJC_METHOD_FAMILY_NONE;
- (id<DeGminoGeobaseSharedMapMapLayer>)newMapLayerWithDeGminoGeobaseSharedMapMapProviderEnum:(DeGminoGeobaseSharedMapMapProviderEnum *)provider OBJC_METHOD_FAMILY_NONE;
- (id<DeGminoGeobaseSharedMapSmartLayer>)newSmartLayerWithNSString:(NSString *)name OBJC_METHOD_FAMILY_NONE;
@end
