//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/MarkerLayer.java
//
//  Created by lena on 24.06.13.
//

void DeGminoGeobaseSharedMapMarkerLayer_unused() {}
