//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/Marker.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoGeobaseSharedDomainImageUrl;
@class DeGminoGeobaseSharedDomainLatLon;

#import "JreEmulation.h"
#import "java/lang/Comparable.h"

@protocol DeGminoGeobaseSharedMapMarker < JavaLangComparable, NSObject >
- (NSString *)getTitle;
- (NSString *)getDescription;
- (void)setLocationWithDeGminoGeobaseSharedDomainLatLon:(DeGminoGeobaseSharedDomainLatLon *)location;
- (DeGminoGeobaseSharedDomainLatLon *)getLocation;
- (DeGminoGeobaseSharedDomainImageUrl *)getIconUrl;
- (int)getInternalId;
@end
