//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /home/lena/meva/issuemap.module/ios/cpy/de/gmino/geobase/shared/map/SmartLayer.java
//
//  Created by lena on 24.06.13.
//

@class DeGminoMevaSharedEntityTypeName;
@protocol DeGminoGeobaseSharedDomainPoi;
@protocol DeGminoGeobaseSharedMapIconRenderer;
@protocol DeGminoGeobaseSharedMapPopupCreator;

#import "JreEmulation.h"

@protocol DeGminoGeobaseSharedMapSmartLayer < NSObject >
- (void)addPoiWithDeGminoGeobaseSharedDomainPoi:(id<DeGminoGeobaseSharedDomainPoi>)o;
- (void)removePoiWithDeGminoGeobaseSharedDomainPoi:(id<DeGminoGeobaseSharedDomainPoi>)o;
- (void)addMarkerIconRendererWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                         withDeGminoGeobaseSharedMapIconRenderer:(id<DeGminoGeobaseSharedMapIconRenderer>)renderer;
- (void)addMarkerPopupCreatorWithDeGminoMevaSharedEntityTypeName:(DeGminoMevaSharedEntityTypeName *)type
                         withDeGminoGeobaseSharedMapPopupCreator:(id<DeGminoGeobaseSharedMapPopupCreator>)creator;
- (void)updatePoiWithDeGminoGeobaseSharedDomainPoi:(id<DeGminoGeobaseSharedDomainPoi>)o;
@end
