/*
 * Copyright © 2010, Data Base Architects, Inc. All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice,
 *       this list of conditions and the following disclaimer in the documentation
 *       and/or other materials provided with the distribution.
 *     * Neither the names of Kalinda Software, DBA Software, Data Base Architects, Itemscript
 *       nor the names of its contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * 
 * Author: Jacob Davies
 */

package org.itemscript.core;

import org.itemscript.core.connectors.GetCallback;
import org.itemscript.core.connectors.PutCallback;
import org.itemscript.core.connectors.RemoveCallback;
import org.itemscript.core.values.JsonCreator;
import org.itemscript.core.values.JsonGetAccess;
import org.itemscript.core.values.JsonPutAccess;
import org.itemscript.core.values.JsonValue;
import org.itemscript.core.values.PutResponse;
import org.itemscript.core.values.RemoveResponse;

/**
 * A JsonSystem provides access to facilities for parsing, storing, and manipulating JSON values.
 * 
 * @author Jacob Davies<br/><a href="mailto:jacob@itemscript.org">jacob@itemscript.org</a>
 *
 */
public interface JsonSystem extends JsonGetAccess, JsonPutAccess, HasSystem, JsonCreator {
    /**
     * The root URL for the system (<code>"mem:/"</code>).
     */
    public static final String ROOT_URL = "mem:/";
    /**
     * The URL under which all Itemscript configuration information is stored.
     */
    public static final String ITEMSCRIPT_URL = ROOT_URL + "/itemscript";
    /**
     * The URL of a blank object available for copying.
     */
    public static final String OBJECT_URL = ITEMSCRIPT_URL + "/object";
    /**
     * The URL of a blank array available for copying.
     */
    public static final String ARRAY_URL = ITEMSCRIPT_URL + "/array";

    /**
     * Copy a value into the system. The original value may come from a different JsonSystem.
     * The value will be converted to a JSON string and then re-parsed, so JsonNative values
     * will not be preserved and JsonString values with a binary value will be converted to base-64
     * encoded strings.
     * 
     * @param value The value to copy.
     * @param toUrl The URL to copy to.
     * @return The PutResponse generated by the put operation.
     */
    public PutResponse copy(JsonValue value, String toUrl);

    /**
     * Copy a value from one URL to another.
     * 
     * @param fromUrl The URL to copy from.
     * @param toUrl The URL to copy to.
     * @return The PutResponse generated by the put operation.
     */
    public PutResponse copy(String fromUrl, String toUrl);

    /**
     * Copy a value from one URL to another, asychronously.
     * 
     * @param fromUrl The URL to copy from.
     * @param toUrl The URL to copy to.
     * @param callback The callback to call when the operation is complete.
     */
    public void copy(String fromUrl, String toUrl, PutCallback callback);

    /**
     * Get a value from the given URL.
     * <p>
     * If the URL is relative, it will be interpreted as relative to the URL "mem:/".
     * 
     * @param url The URL to get the value from.
     * @return The value returned from the URL.
     */
    public JsonValue get(String url);

    /**
      * Get a value from the given URL, asynchronously.
      * <p>
      * If the URL is relative, it will be interpreted as relative to the URL "mem:/".
      * <p>
      * Calls the given callback when the value has been retrieved.
      * 
      * @param url The URL to get the value from.
      * @param callback Called when the value is returned.
      */
    public void get(String url, GetCallback callback);

    /**
     * Parse the contents of the given string as JSON.
     * 
     * @param json The string containing JSON to be parsed.
     * @return The JsonValue corresponding to the string.
     */
    public JsonValue parse(String json);

    /**
     * Parse the contents of the given Reader as JSON.
     * <p>
     * The argument is specified as Object only because GWT does not contain Reader.
     * <p>
     * Note: this method is inoperative in the GWT environment.
     * 
     * @param reader The Reader to parse.
     * @return The JsonValue corresponding to the contents of the Reader.
     */
    public JsonValue parseReader(Object reader);

    /**
     * Put a value at the given URL.
     * 
     * @param url The URL where the value is to be put.
     * @param value The value to put.
     * @return The PutResponse returned by the put operation.
     */
    public PutResponse put(String url, JsonValue value);

    /**
     * Put a value at the given URL, calling the given callback when the operation is complete.
     * 
     * @param url The URL where the value is to be put.
     * @param value The value to put.
     * @param callback Called when the put operation is complete.
     */
    public void put(String url, JsonValue value, PutCallback callback);

    /**
     * Remove the value at the given URL.
     * 
     * @param url The URL of the value to remove.
     * @return The RemoveResponse returned by the remove operation.
     */
    public RemoveResponse remove(String url);

    /**
     * Remove the value at the given URL, calling the given callback when the operation is complete.
     * 
     * @param url The URL of the value to remove.
     * @param callback Called when the remove operation has completed.
     */
    public void remove(String url, RemoveCallback callback);

    /**
     * Get the {@link JsonUtil} object for this system. The JsonUtil object contains various implementation
     * methods that may be useful but aren't really part of the core system interface.
     * 
     * @return The associated JsonUtil.
     */
    public JsonUtil util();

    /**
     * Set a constant in this JsonSystem.
     * 
     * @param name The name of the constant.
     * @param value The value of the constant.
     * @throws ItemscriptError If a constant with this name has already been set.
     */
    public void setConstant(String name, String value);

    /**
     * Get a constant from this JsonSystem.
     * 
     * @param name The name of the constant.
     * @return The value of the constant.
     * @throws ItemscriptError If a constant with this name has not been set.
     */
    public String constant(String name);
}